// examples/react-example.tsx
/**
 * React Integration Example
 * Shows how to use Pulse with React
 */

import React from 'react';
import { useSignal, useComputed, usePulseEffect } from '../src/integrations/react';
import { signal, computed } from '../src/index';

// Shared signal (can be in a separate file)
const countSignal = signal(0);
const nameSignal = signal('World');

export function Counter() {
  const [count, setCount] = useSignal(countSignal);
  const doubled = useComputed(computed(() => count * 2));

  return (
    <div>
      <p>Count: {count}</p>
      <p>Doubled: {doubled}</p>
      <button onClick={() => setCount(count + 1)}>Increment</button>
      <button onClick={() => setCount(count - 1)}>Decrement</button>
    </div>
  );
}

export function Greeting() {
  const [name, setName] = useSignal(nameSignal);

  usePulseEffect(() => {
    console.log('Name changed to:', name);
  }, [name]);

  return (
    <div>
      <input
        value={name}
        onChange={(e) => setName(e.target.value)}
        placeholder="Enter your name"
      />
      <p>Hello, {name}!</p>
    </div>
  );
}

// examples/vue-example.vue
<template>
  <div>
    <h1>Pulse Vue Example</h1>
    <p>Count: {{ count }}</p>
    <p>Doubled: {{ doubled }}</p>
    <button @click="increment">Increment</button>
    <button @click="decrement">Decrement</button>
  </div>
</template>

<script setup lang="ts">
import { useSignal, useComputed } from '../src/integrations/vue';
import { signal, computed } from '../src/index';

const countSignal = signal(0);
const count = useSignal(countSignal);
const doubled = useComputed(computed(() => count.value * 2));

const increment = () => {
  countSignal.set(countSignal() + 1);
};

const decrement = () => {
  countSignal.set(countSignal() - 1);
};
</script>
